pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/sachdeore/java-maven-app.git', branch: 'master'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t java-maven-app .'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker rm -f java-maven-app || true'
                sh 'docker run -d -p 8080:8080 --name java-maven-app java-maven-app'
            }
        }
    }
}
